# Site Settings
locale : "ko-KR"
title  : "Gyu-Yong Jeong"
url    : "https://jeong000307.github.io"
baseurl: ""

markdown: kramdown

tracking_id: "UA-132865468-1"

permalink: none

footer		: yes
footer_url	: "https://jeong000307.github.io"
footer_text	: "By Gyu-Yong Jeong"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
# 	link: "/researcher/"
 - name: "GitHub"
   link: "https://github.com/jeong000307"
 - name: "Contact"
   link: "contact"

collections:
  posts:
    output: true
  projects:
    output: true
  researchs:
    output: true