# Site Settings
locale                   : "ko-KR"
title                    : "jeong000307's Blog"
url                      : "https://jeong000307.github.io"
baseurl:

comments:
	provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2", "utterances", "custom"
	disqus:
		shortname          : "jeong000307" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

analytics:
	provider	             : "google" # false (default), "google", "google-universal", "custom"
	google:
		tracking_id          : "UA-132865468-1"
    	anonymize_ip         : # true, false (default)

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
