# Site Settings
locale  : "ko-KR"
title   : "Gyu-Yong Jeong's Blog"
url     : "https://jeong000307.github.io"
baseurl : ""
author  : "jeong000307"

markdown: kramdown

kramdown:
    input: GFM
    syntax_hightlighter: rouge

plugins:
    - jekyll-relative-links

tracking_id: "UA-132865468-1"
discus-identifier: jeong000307

permalink: none

footer		: yes
footer_url	: "https://jeong000307.github.io"
footer_text	: "By Gyu-Yong Jeong"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Contact"
    link: "contact"
    ext : "false"
  - name: "GitHub"
    link: "https://github.com/jeong000307"
    ext : "true"